# Generated by Django 2.2.13 on 2020-06-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commit',
            options={'ordering': ('-date',), 'verbose_name': 'Commit', 'verbose_name_plural': 'Commits'},
        ),
        migrations.AlterModelOptions(
            name='repo',
            options={'ordering': ('-date',), 'verbose_name': 'Repo', 'verbose_name_plural': 'Repos'},
        ),
        migrations.AddField(
            model_name='repo',
            name='user',
            field=models.CharField(default='fabiomsrs', max_length=150, verbose_name='Usuário'),
            preserve_default=False,
        ),
    ]
